export type ExperienceCategory = "vibe" | "food" | "hidden";

export interface ExperienceItem {
    id: string;
    title: string;
    description: string;
    city: string;
    vibe: string;
    category: ExperienceCategory;
    budget: "low" | "medium";
    lat: number;
    lng: number;
}

export const EXPERIENCES: ExperienceItem[] = [
    // —— Vibes (26)
    {
        id: "kadikoy-nightwalk",
        title: "Kadikoy Night Walk",
        description:
            "Live music stops and student-friendly cafes around Moda.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "low",
        lat: 40.9865,
        lng: 29.0263,
    },
    {
        id: "balat-photo-route",
        title: "Balat Color Route",
        description: "Colorful streets, antiques and coffee breaks in Balat.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0291,
        lng: 28.9497,
    },
    {
        id: "beyoglu-rooftop-evening",
        title: "Beyoglu Rooftop Evening",
        description: "Sunset rooftop spots and affordable student menus.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "medium",
        lat: 41.0343,
        lng: 28.977,
    },
    {
        id: "uskudar-coast-chill",
        title: "Uskudar Coast Chill",
        description: "Calm Bosphorus walk with tea stops by the coast.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "low",
        lat: 41.0236,
        lng: 29.0152,
    },
    {
        id: "istiklal-golden-hour",
        title: "Istiklal Golden Hour Stroll",
        description:
            "Street performers and historic passages before the crowds peak.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0356,
        lng: 28.979,
    },
    {
        id: "besiktas-bosphorus-sunset",
        title: "Besiktas Bosphorus Sunset",
        description:
            "Ferry arrivals, tea gardens and student picnic spots by the water.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "low",
        lat: 41.0422,
        lng: 29.0089,
    },
    {
        id: "karakoy-after-dark",
        title: "Karakoy After Dark",
        description:
            "Converted warehouses, craft bars and Galata bridge lights.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "medium",
        lat: 41.0238,
        lng: 28.9747,
    },
    {
        id: "moda-seaside-loop",
        title: "Moda Seaside Loop",
        description: "Slow loops along Moda shore with ice cream and benches.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "low",
        lat: 40.9847,
        lng: 29.0259,
    },
    {
        id: "nisantasi-window-evening",
        title: "Nisantasi Window Evening",
        description:
            "Tree-lined streets, galleries and budget bites between boutiques.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "medium",
        lat: 41.0469,
        lng: 28.9858,
    },
    {
        id: "ortakoy-mezze-night",
        title: "Ortakoy Mezze Night",
        description:
            "Mosque-lit waterfront and waffle stalls sharing one plaza.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "low",
        lat: 41.0474,
        lng: 29.0269,
    },
    {
        id: "yildiz-park-picnic",
        title: "Yildiz Park Picnic",
        description:
            "Shaded hills and ponds above Ortakoy—bring snacks from Besiktas.",
        city: "Istanbul",
        vibe: "nature",
        category: "vibe",
        budget: "low",
        lat: 41.0469,
        lng: 29.0118,
    },
    {
        id: "chora-village-walk",
        title: "Chora Quarter Walk",
        description:
            "Stone lanes around Chora with murals and quiet courtyard cafes.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0315,
        lng: 28.9395,
    },
    {
        id: "buyukada-ring-ride",
        title: "Buyukada Ring Ride",
        description:
            "Rent a bike for the island loop—pine air and sea on both sides.",
        city: "Istanbul",
        vibe: "nature",
        category: "vibe",
        budget: "medium",
        lat: 40.8694,
        lng: 29.1208,
    },
    {
        id: "cihangir-steep-streets",
        title: "Cihangir Steep Streets",
        description:
            "Cats, balconies and third-wave cafes climbing toward Galata.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0319,
        lng: 28.9856,
    },
    {
        id: "kadife-kale-view",
        title: "Kadife Kale View Walk",
        description:
            "Panorama over Kadikoy roofs—golden hour without club prices.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "low",
        lat: 40.9912,
        lng: 29.0268,
    },
    {
        id: "rumeli-hisari-cliffs",
        title: "Rumeli Hisari Cliffs",
        description:
            "Fort views and breezy walks—pair with a tea stop in Bebek.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0847,
        lng: 29.0566,
    },
    {
        id: "bebek-boardwalk",
        title: "Bebek Boardwalk",
        description:
            "Yacht silhouettes and jogging paths along the European shore.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "medium",
        lat: 41.0769,
        lng: 29.0438,
    },
    {
        id: "bomonti-night-cluster",
        title: "Bomonti Night Cluster",
        description:
            "Converted brewery district—concerts and courtyard venues.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "medium",
        lat: 41.0597,
        lng: 28.9769,
    },
    {
        id: "sultanahmet-blue-hour",
        title: "Sultanahmet Blue Hour",
        description:
            "Open squares between Hagia Sophia and the Blue Mosque after tours thin out.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0055,
        lng: 28.9769,
    },
    {
        id: "caddebostan-breeze",
        title: "Caddebostan Breeze",
        description:
            "Long seaside promenade—watch windsurfers and share simit.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "low",
        lat: 40.9698,
        lng: 29.0638,
    },
    {
        id: "pera-evening-jazz",
        title: "Pera Evening Jazz",
        description:
            "Historic hotels and intimate venues—check student nights.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "medium",
        lat: 41.0328,
        lng: 28.9749,
    },
    {
        id: "belgrad-forest-gate",
        title: "Belgrad Forest Gate Walk",
        description:
            "Shaded trails at the northern edge—early starts beat weekend traffic.",
        city: "Istanbul",
        vibe: "nature",
        category: "vibe",
        budget: "low",
        lat: 41.1769,
        lng: 28.9548,
    },
    {
        id: "kuzguncuk-colored-houses",
        title: "Kuzguncuk Colored Houses",
        description:
            "Painted facades, synagogue corners and Bosphorus glimpses.",
        city: "Istanbul",
        vibe: "culture",
        category: "vibe",
        budget: "low",
        lat: 41.0368,
        lng: 29.0296,
    },
    {
        id: "bakirkoy-coastal-strip",
        title: "Bakirkoy Coastal Strip",
        description:
            "West-side sunset planes and park benches facing the Marmara.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "vibe",
        budget: "low",
        lat: 40.9769,
        lng: 28.8739,
    },
    {
        id: "taksim-side-streets",
        title: "Taksim Side Streets",
        description:
            "Branch off Istiklal into loud meyhanes and indie DJ bars.",
        city: "Istanbul",
        vibe: "nightlife",
        category: "vibe",
        budget: "low",
        lat: 41.0369,
        lng: 28.985,
    },
    {
        id: "camlica-hill-breeze",
        title: "Camlica Hill Breeze",
        description:
            "European skyline from the Asian ridge—tea gardens on both peaks.",
        city: "Istanbul",
        vibe: "nature",
        category: "vibe",
        budget: "low",
        lat: 41.0276,
        lng: 29.0665,
    },

    // —— Food (26)
    {
        id: "eminonu-street-food",
        title: "Eminonu Street Food",
        description:
            "Balik ekmek, kokorec and tea with Bosphorus views.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0164,
        lng: 28.9709,
    },
    {
        id: "kadikoy-fish-market-bites",
        title: "Kadikoy Fish Market Bites",
        description:
            "Meze counters, pickles and lokanta spreads around the market.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 40.9905,
        lng: 29.0248,
    },
    {
        id: "karakoy-breakfast-row",
        title: "Karakoy Breakfast Row",
        description:
            "Weekend queues for menemen and börek facing the Golden Horn.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0235,
        lng: 28.9758,
    },
    {
        id: "ferikoy-organic-saturday",
        title: "Ferikoy Organic Saturday",
        description:
            "Farm cheeses, olives and picnic supplies before Bomonti brunch.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0548,
        lng: 28.9787,
    },
    {
        id: "besiktas-kofte-crawl",
        title: "Besiktas Kofte Crawl",
        description:
            "Legendary köfte shops near the ferry pier—share plates.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0428,
        lng: 29.0078,
    },
    {
        id: "uskudar-manti-tea",
        title: "Uskudar Manti Trail",
        description:
            "Tiny mantı shops and çay gardens behind the ferry terminals.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.022,
        lng: 29.0145,
    },
    {
        id: "balat-brunch-rooftops",
        title: "Balat Brunch Rooftops",
        description:
            "Terraces over red roofs—many student-friendly set menus.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0283,
        lng: 28.9515,
    },
    {
        id: "samatya-seafood-alley",
        title: "Samatya Seafood Alley",
        description:
            "Old-city meyhane lanes—mezze first, fish grilled to order.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0064,
        lng: 28.9327,
    },
    {
        id: "fatih-lokanta-lunch",
        title: "Fatih Lokanta Lunch",
        description:
            "Tray service with rotating güveç and olive-oil dishes.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0198,
        lng: 28.9497,
    },
    {
        id: "galata-dessert-hop",
        title: "Galata Dessert Hop",
        description:
            "Künefe, ice cream and helva counters circling the tower.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0256,
        lng: 28.9741,
    },
    {
        id: "spice-bazaar-sampling",
        title: "Spice Bazaar Sampling",
        description:
            "Dates, Turkish delight trials and pickle vendors—snack as you walk.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0165,
        lng: 28.9705,
    },
    {
        id: "ortakoy-kumpir-square",
        title: "Ortakoy Kumpir Square",
        description:
            "Stuffed potatoes by the mosque—split toppings with friends.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0471,
        lng: 29.0275,
    },
    {
        id: "moda-coffee-strip",
        title: "Moda Coffee Strip",
        description:
            "Third-wave shots and pastries along residential side streets.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 40.9858,
        lng: 29.0275,
    },
    {
        id: "cihangir-meze-night",
        title: "Cihangir Meze Night",
        description:
            "Small plates and rakı-friendly terraces without tourist pricing.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0324,
        lng: 28.9868,
    },
    {
        id: "bebek-borek-waterfront",
        title: "Bebek Börek Waterfront",
        description:
            "Layered börek shops facing moored boats—grab tea next door.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0775,
        lng: 29.0445,
    },
    {
        id: "sirkeci-kebab-pit-stop",
        title: "Sirkeci Kebab Pit Stop",
        description:
            "Late döner and pide blocks serving commuters and students.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0139,
        lng: 28.9766,
    },
    {
        id: "atasehir-student-eats",
        title: "Atasehir Student Eats",
        description:
            "Campus-adjacent döner and çiğ köfte clusters after classes.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 40.9889,
        lng: 29.1248,
    },
    {
        id: "arnavutkoy-fish-grills",
        title: "Arnavutkoy Fish Grills",
        description:
            "Wooden houses and tiny grills plating the catch of the day.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0674,
        lng: 29.0428,
    },
    {
        id: "tarabya-brunch-marina",
        title: "Tarabya Brunch Marina",
        description:
            "North-shore cafes—weekday menus stretch budgets farther.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.1375,
        lng: 29.0389,
    },
    {
        id: "zeyrek-lost-lokanta",
        title: "Zeyrek Lokanta Lane",
        description:
            "Hillside eateries near Süleymaniye with tray lunches.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0195,
        lng: 28.9598,
    },
    {
        id: "besiktas-kumpir-backstreets",
        title: "Besiktas Ortakoy Connector Snacks",
        description:
            "Mid-route gözleme and juice bars between Besiktas and Ortakoy.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.045,
        lng: 29.0189,
    },
    {
        id: "maltepe-coastal-midye",
        title: "Maltepe Coastal Midye",
        description:
            "Stuffed mussels along the Asian Marmara promenade.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 40.9369,
        lng: 29.1258,
    },
    {
        id: "nisantasi-light-bites",
        title: "Nisantasi Light Bites",
        description:
            "Salads, soups and bakeries between gallery hops.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 41.0482,
        lng: 28.9875,
    },
    {
        id: "florya-fish-gardens",
        title: "Florya Fish Gardens",
        description:
            "West Marmara shore—family grills and çay gardens.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 40.9827,
        lng: 28.7937,
    },
    {
        id: "beyoglu-late-doner",
        title: "Beyoglu Late Doner",
        description:
            "Post-midnight döner windows feeding Istiklal night crowds.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "low",
        lat: 41.0362,
        lng: 28.9805,
    },
    {
        id: "heybeliada-seaside-mezze",
        title: "Heybeliada Seaside Mezze",
        description:
            "Island ferries then harbor-side meyhane terraces.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "food",
        budget: "medium",
        lat: 40.8779,
        lng: 29.0916,
    },

    // —— Hidden gems (26)
    {
        id: "fenerbahce-hidden-pier",
        title: "Fenerbahce Hidden Pier",
        description:
            "Locals-only benches and calm water east of Kalamis marina.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 40.9658,
        lng: 29.0389,
    },
    {
        id: "yeldeğirmeni-backlot-art",
        title: "Yeldegirmeni Backlot Art",
        description:
            "Murals and tiny studios between Kadikoy and Haydarpasa.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 40.9938,
        lng: 29.0318,
    },
    {
        id: "bulgurlu-stair-gardens",
        title: "Bulgurlu Stair Gardens",
        description:
            "Terraced tea plots climbing toward Camlica—few tourists.",
        city: "Istanbul",
        vibe: "nature",
        category: "hidden",
        budget: "low",
        lat: 41.0218,
        lng: 29.0728,
    },
    {
        id: "zeyrek-panorama-stairs",
        title: "Zeyrek Panorama Stairs",
        description:
            "Hidden viewpoints over the Golden Horn behind timber houses.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0197,
        lng: 28.9557,
    },
    {
        id: "suleymaniye-library-quiet",
        title: "Suleymaniye Library Quiet",
        description:
            "Courtyard benches and lesser-known terrace angles by the complex.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0159,
        lng: 28.9645,
    },
    {
        id: "kalamis-hidden-jetty",
        title: "Kalamis Hidden Jetty",
        description:
            "Small wooden jetty paths west of Moda—bring a book.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 40.9635,
        lng: 29.0418,
    },
    {
        id: "eyup-cemetery-path",
        title: "Eyup Cemetery Cypress Path",
        description:
            "Shaded uphill walk with sweeping Horn views—respectful pace.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0486,
        lng: 28.9348,
    },
    {
        id: "pierre-loti-cable-quiet",
        title: "Pierre Loti Cable Quiet",
        description:
            "Skip peak hours for tea terraces above Eyup—golden Horn ribbons.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 41.0478,
        lng: 28.9238,
    },
    {
        id: "anadoluhisari-backstreets",
        title: "Anadoluhisari Backstreets",
        description:
            "Castle glimpses through ivy walls and boat-builder lanes.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0816,
        lng: 29.0657,
    },
    {
        id: "ataturk-arboretum-loop",
        title: "Ataturk Arboretum Loop",
        description:
            "Timed entry forest paths—check student discounts mid-week.",
        city: "Istanbul",
        vibe: "nature",
        category: "hidden",
        budget: "medium",
        lat: 41.1775,
        lng: 29.0538,
    },
    {
        id: "kariye-mosaic-quiet-hour",
        title: "Kariye Mosaic Quiet Hour",
        description:
            "Arrive at opening for empty nave light on Byzantine mosaics.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "medium",
        lat: 41.0316,
        lng: 28.9392,
    },
    {
        id: "cukurcuma-antique-nooks",
        title: "Cukurcuma Antique Nooks",
        description:
            "Basement shops and cinema posters between cafes.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0315,
        lng: 28.9817,
    },
    {
        id: "haydarpasa-rail-glimpse",
        title: "Haydarpasa Rail Glimpse",
        description:
            "Platform edges and seaside angles on the historic station shell.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 40.9956,
        lng: 29.0189,
    },
    {
        id: "kanlica-yogurt-hill",
        title: "Kanlica Yogurt Hill",
        description:
            "Famous yogurt counters plus quiet uphill lanes behind them.",
        city: "Istanbul",
        vibe: "food-drink",
        category: "hidden",
        budget: "low",
        lat: 41.1058,
        lng: 29.0655,
    },
    {
        id: "polonezkoy-pine-edge",
        title: "Polonezkoy Pine Edge",
        description:
            "Village lanes and pancake houses—forest air without crowds.",
        city: "Istanbul",
        vibe: "nature",
        category: "hidden",
        budget: "medium",
        lat: 41.1067,
        lng: 29.1634,
    },
    {
        id: "bayrampasa-green-strip",
        title: "Bayrampasa Linear Park Strip",
        description:
            "Elevated park threading apartments—sunset joggers and picnics.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 41.0498,
        lng: 28.9017,
    },
    {
        id: "maslak-backlot-walk",
        title: "Maslak Backlot Walk",
        description:
            "Sculpture pockets between towers—oddly calm lunch breaks.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.1128,
        lng: 29.0178,
    },
    {
        id: "yenikapi-artificial-reef-view",
        title: "Yenikapi Reef Walk",
        description:
            "Long seawalls and kite flyers—wide horizon west of Sirkeci.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 41.0053,
        lng: 28.9529,
    },
    {
        id: "silivri-weekend-dunes",
        title: "Silivri Dunes Breeze",
        description:
            "Far-west beaches for budget day trips—check bus schedules.",
        city: "Istanbul",
        vibe: "nature",
        category: "hidden",
        budget: "low",
        lat: 41.0739,
        lng: 28.2478,
    },
    {
        id: "sariyer-hidden-creek",
        title: "Sariyer Hidden Creek",
        description:
            "Forest creek picnics north of the city—combine with beach buses.",
        city: "Istanbul",
        vibe: "nature",
        category: "hidden",
        budget: "low",
        lat: 41.1669,
        lng: 29.0532,
    },
    {
        id: "eminonu-rooftop-tea",
        title: "Eminonu Rooftop Tea Corners",
        description:
            "Upper floors above spice lanes—cheap çay with horn vistas.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 41.0175,
        lng: 28.9718,
    },
    {
        id: "uskudar-valide-atik-mosque-yard",
        title: "Valide Atik Courtyard",
        description:
            "Stone courtyard calm blocks from the ferry bustle.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0248,
        lng: 29.0168,
    },
    {
        id: "beykoz-kavagi-forest-glimpse",
        title: "Beykoz Kavagi Forest Glimpse",
        description:
            "Pocket forests before Anadolukavağı—tea gardens with ship traffic.",
        city: "Istanbul",
        vibe: "nature",
        category: "hidden",
        budget: "low",
        lat: 41.1798,
        lng: 29.0897,
    },
    {
        id: "moda-cat-garden-benches",
        title: "Moda Cat Garden Benches",
        description:
            "Shaded pocket park loved by neighborhood cats and readers.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 40.9879,
        lng: 29.0289,
    },
    {
        id: "sirkeci-underpass-murals",
        title: "Sirkeci Underpass Murals",
        description:
            "Rotating street art tunnels linking tram lines—quick photo loop.",
        city: "Istanbul",
        vibe: "culture",
        category: "hidden",
        budget: "low",
        lat: 41.0145,
        lng: 28.9769,
    },
    {
        id: "bakirkoy-hidden-book-cafe",
        title: "Bakirkoy Book Cafe Corners",
        description:
            "Second-hand shelves and çay deals away from the marina crowds.",
        city: "Istanbul",
        vibe: "relaxation",
        category: "hidden",
        budget: "low",
        lat: 40.9795,
        lng: 28.8715,
    },
];
